name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # كل يوم
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-pacman
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Pacman Graph
        uses: Platane/snk@v3
        with:
          github_user_name: Omar-eng-sys
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg
          theme: pacman

      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "update pacman contribution graph"
