name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # كل يوم الساعة 12 بالليل
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-pacman
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pacman Graph
        uses: platane/pacman@v1
        with:
          github_user_name: Omar-eng-sys
          mode: time
          output: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg

      - name: Commit & Push Pacman Graph
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "update pacman contribution graph"
